[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mrkhan9914626", email = "khan9914626@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.42.0",
]

[project.scripts]
project = "project:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
